/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CurrentEnvironment: typeof import('./src/components/CurrentEnvironment/CurrentEnvironment.vue')['default']
    FanControl: typeof import('./src/components/FanControl/FanControl.vue')['default']
    LanguageSwitch: typeof import('./src/components/LanguageSwitch/LanguageSwitch.vue')['default']
    LedSettings: typeof import('./src/components/LedSettings/LedSettings.vue')['default']
    Loading: typeof import('./src/components/Loading/Loading.vue')['default']
    Navbar: typeof import('./src/components/Navbar/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SensorInfo: typeof import('./src/components/SensorInfo/SensorInfo.vue')['default']
    SerialConfig: typeof import('./src/components/SerialConfig/SerialConfig.vue')['default']
    SettingsShortcuts: typeof import('./src/components/SettingsShortcuts/SettingsShortcuts.vue')['default']
    StaticAccessPointSettings: typeof import('./src/components/StaticAccessPointSettings/StaticAccessPointSettings.vue')['default']
    SystemInfo: typeof import('./src/components/SystemInfo/SystemInfo.vue')['default']
  }
}
